---
name: Salmon and Rice Bowl
description: A yummy mixture of salmon and white rice topped with a healthy \
              dose of siracha and mayo along with a dash of soy sauce. \
              Combining it with dried seaweed wraps can take it to the next \
              level.
steps:
  - Preheat: 420
  - Prepare salmon on baking sheet
