[workspace]
resolver = "2"
members = [
  "common",
  "cook-chef",
  "driver",
  "prep-chef",
]

[workspace.lints.rust]
unsafe_code = "forbid"

# TODO: check out [profile] table options for binary optimization settings